### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by Karlen92** [cloudtrust/keycloak-authorization#10]
I have Keycloack up and running. When I try to execute the following command

`sudo install -v -m0755 -o keycloak -g keycloak -d target/keycloak-authorization-3.4.3.Final.jar /opt/keycloak/modules/system/layers/authorization/io/cloudtrust/keycloak-authorization/main/`

I get this error
`install: keycloak: Invalid argument`

Does anyone know what might be the issue?

**Comment by fperot74** [comment]
Are you still using keycloak 3.4.3? (we are currently upgrading our modules to keycloak 11.0.2)
Our team does not have time to work on this module and as it is a pretty old version of Keycloak, we can't tell about your issue anymore. Perhaps some other users?
This module would need to be upgraded to a more recent version of Keycloak or rewritten for a new version of Keycloak. As it is not in our current scope, any contribution will be gratefully accepted.

**Comment by Karlen92** [comment]
@fperot74 Thanks for the reply. I use KeyCloack 11.0.2, but the command which is the installation section of the Readme file does not work even with version 10.0.0

`sudo install -v -m0755 -o keycloak -g keycloak -d target/keycloak-authorization-10.0.0.Final.jar /opt/keycloak/modules/system/layers/authorization/io/cloudtrust/keycloak-authorization/main/`

The same error persists with this also.

**Comment by fperot74** [comment]
Sorry for the delay...
I guess you are not using Keycloak with the user "keycloak" in the group "keycloak"... Replace -o and -g parameters with the owner and the group of the process which is executing Keycloak
