### ISSUE TITLE
Questions about plugin upgrade steps

### ISSUE THREAD

**Issue by paco-coutaud** [cloudtrust/keycloak-authorization#11]
Hi,

After successfully installed the current plugin on a 3.4.3.Final Keycloak docker container instance, we are proceeding with plugin upgrade. We removed the [WsFed dependency](https://github.com/cloudtrust/keycloak-wsfed) as we don't use it. (Few more steps not mentionned were required (test code removal, parent property set to keycloak in theme.properties...).

So, now we have a plugin working fine with Keycloak 3.4.3.Final, we are targeting to upgrade the plugin to be compatible with Keycloak v11, migrating to final major versions (3.4.3.Final -> 4.8.3.Final -> 5.0.0...) one at a time.

Following readme [instructions](https://github.com/cloudtrust/keycloak-authorization#how-to-update-the-code-when-keycloak-changes-version-number) we have replaced old Keycloak classes with version 4.8.3.Final ones and solved all main code compilation issues (not test compilation issues).

The only remaining issue is related to the deletion of [org.keycloak.authorization.util.Permission](https://github.com/keycloak/keycloak/blob/4.8.3.Final/services/src/main/java/org/keycloak/authorization/util/Permissions.java) class' "permits" method. We are not able to find a suitable replacement in 4.8.3 that would perform similar tasks (Filter results and look for granted permissions).

Do you have any clues on how we could solve this issue ?

We can provide code changes if needed.

Thanks in advance !

Regards,
Paco

**Comment by paco-coutaud** [comment]
Hi,

Any one can help us on this topic ?
@fperot74 ? :)

Thanks in advance,
Paco

**Comment by fperot74** [comment]
Hi Paco,

We are not using/maintaining this Keycloak module since 4.8.3...
I only started to upgrade it to Keycloak 6.0.1 but we decided to give up with this module. I can remember it was compiling correctly but tests were failing and I had no time to investigate.
I just open a PR so that you can check how I managed the Permission case: cloudtrust/keycloak-authorization#12

Don't hesitate to submit a PR to share an up-to-date solution with the community if you have manage to do so.

**Comment by paco-coutaud** [comment]
Hi @fperot74 

We updated the plugin for Keycloak 12.0.2 based on your previous PR, but the plugin doesn't seem to be executed once deployed. For debugging purposes, we raise voluntarly several exceptions in different places of the code and we couldn't observe any of them in the Keycloak logs (Debug mode).

We used the same process as described in the Readme but we adapted some information to work with keycloak 12.0.2.

Do you have any clues (like an option to take into account extensions into keycloak for example or whatever) that could help us to test our code ? Perhaps we are missing something.

Thanks a lot in advance,
Paco
