### ISSUE TITLE
Does the  authorization resources tab makes sense for the local authorization?

### ISSUE THREAD

**Issue by AlistairDoswald** [cloudtrust/keycloak-authorization#6]
Currently when a client becomes a resource server (by allowing authorization), the default resource allowing access to the entire client is created by default. It is then possible to add and remove resources (including the default resource) from the resource tab.

For local resources however, this makes no sense, as only the default resource should ever be considered. We should decide if we keep this resources tab for local authorization, or if we remove it/make it uneditable. 

Likewise, we should consider if we should ensure that the default resource always exists.

**Comment by AlistairDoswald** [comment]
Beyond this question, what other GUI/code elements make no sense for the local authorization service?

**Comment by yelhouti** [comment]
IMO, the same policies can be used for local and remote (UMA) authorization. scopes ans resources on th other hand don't make much sense. evaluate should be modified, and the added (local config) should be present for the export feature.

Still there are few problems:

- When Authorization is disabled, Keycloak (4.3.4) removes all the data stored for the resource server from the database, unless we change that behavior we want be able to integrate local with remote authorizations.
- When activating authorizations, client account are activated (to be able to use UMA), and the client is therefore made confidential. On the other hand local authorizations should work with public clients.
- UMA 2.0 will be introduced in keycloak 4, and all this code might change we should check that before mocing forward.
