### ISSUE TITLE
Update or Archive this repository

### ISSUE THREAD

**Issue by oscarlofwenhamn** [cloudtrust/keycloak-authorization#9]
Current version is confirmed to be compatible with Keycloak 3.4.3 Final, current Keycloak version is 9.0.2. If this project is dead, it would be helpful with a notation declaring it as such, or if it is alive and simply on ice a notation explaining that, since this is listed on the Keycloak site as one of the community maintained Extensions. 
If not that, a section detailing directions for potential contributors would be good, to make it easier for community members to contribute.

This plugin would solve a major problem we are currently facing, and as such it would be great to know if there is any hope of seeing an updated version of it or if we have to try to find another solution. 

Keeping my fingers crossed for a potential update, this looks to be a great concept for an extension!

**Comment by fperot74** [comment]
Thanks for your interest, @oscarlofwenhamn
We are sorry to tell you that there is no new scheduled version yet.
This module is not abandoned but as we are currently pretty busy with many other topics, this is not "high priority" in our task list. PRs are always welcome ;-)

**Comment by oscarlofwenhamn** [comment]
Glad to hear it's not abandoned, hopefully you'll be able to get to a new version in not too long. Hopefully I will be able check it out and see if I can help when I've cleared some tasks, though as mentioned a section for contributors would be helpful. Cheers!
